### ISSUE TITLE
Bug in IsBiconnectedDigraphs

### ISSUE THREAD

**Issue by james-d-mitchell** [gap-packages/Digraphs#102]
gap> D := Digraph([[2, 4, 5], [1, 4], [4, 7], [1, 2, 3, 5, 6, 7],
    >                  [1, 4], [4, 7], [3, 4, 6]]);
    <digraph with 7 vertices, 20 edges>
    gap> IsBiconnectedDigraph(D);
    true
    gap> H := DigraphRemoveVertex(D, 4);
    <digraph with 6 vertices, 8 edges>
    gap> IsConnectedDigraph(H);
    false

**Comment by wilfwilson** [comment]
As I'm sure you know, the source of the bug lies in `ArticulationPoints`, rather than in `IsBiconnectedDigraph` itself.

Here's another example:
```
gap> gr := DigraphFromGraph6String("FlCX?");
<digraph with 7 vertices, 16 edges>
gap> ArticulationPoints(gr);
[ 3 ]
gap> Filtered([1 .. 7], v -> not IsConnectedDigraph(DigraphRemoveVertex(gr, v)));
[ 3, 4 ]
```

**Comment by wilfwilson** [comment]
I think you have to change `gap/attr.gi:73` from `low[v] := low[w];` to `low[v] := num[w];`
