### ISSUE TITLE
Why does homos.h include x86intrin.h?

### ISSUE THREAD

**Issue by wilfwilson** [gap-packages/Digraphs#147]
I've no idea about all this stuff, but I noticed on https://build.opensuse.org/package/view_file/science/gap-digraphs/0001-Drop-bad-include-of-x86intrin.h.patch?expand=1 that they have removed the line `#include <x86intrin.h>` from `homos.h`, with the commit message:
```
Trying to include it does break compilation on anything but x86, and even
on x86 it is completely unnecessary, as builtins are "just there".

Signed-off-by: Stefan Brüns <stefan.bruens@rwth-aachen.de>
```
Are they onto something? Everything on my computer seems to work fine when that line is removed.

**Comment by james-d-mitchell** [comment]
How on earth did you find that?? I'll investigate on Monday.

**Comment by wilfwilson** [comment]
It was by chance, following link after link...

**Comment by wilfwilson** [comment]
Removed in #152
