### ISSUE TITLE
Read DIMACS format

### ISSUE THREAD

**Issue by james-d-mitchell** [gap-packages/Digraphs#15]
Originally reported by: **Christopher Jefferson (Bitbucket: [ChrisJefferson](http://bitbucket.org/ChrisJefferson), GitHub: [ChrisJefferson](http://github.com/ChrisJefferson))**

---

Is there any way to read the 'DIMACS' format in Digraphs? I couldn't find it.

---
- Bitbucket: https://bitbucket.org/james-d-mitchell/digraphs/issue/15

**Comment by mtorpey** [comment]
This is merged and done!  I've added a Trello card for dreadnaut format.
