### ISSUE TITLE
'make doc' is confusing

### ISSUE THREAD

**Issue by james-d-mitchell** [gap-packages/Digraphs#16]
Originally reported by: **Christopher Jefferson (Bitbucket: [ChrisJefferson](http://bitbucket.org/ChrisJefferson), GitHub: [ChrisJefferson](http://github.com/ChrisJefferson))**

----------------------------------------

The 'make doc' target in the Makefile tries to run makedoc.g, which doesn't exist.

I would recommend (in order of ease), one of the following changes to Makefile.in.

1) Just remove the 'doc' and 'doc/manual.six' targets
2) Replace them with something like:

.PHONY: doc

doc:
	(echo 'LoadPackage("digraphs"); DigraphsMakeDoc();' | $(GAPROOT)/bin/gap.sh -A)

----------------------------------------
- Bitbucket: https://bitbucket.org/james-d-mitchell/digraphs/issue/16

**Comment by james-d-mitchell** [comment]
This is now resolved by the introduction of the `makedoc.g` file. @ChrisJefferson can I close the issue?

**Comment by ChrisJefferson** [comment]
Yup

**Comment by james-d-mitchell** [comment]
Great thanks!
