### ISSUE TITLE
Multidigraphs and transformations seems wrong

### ISSUE THREAD

**Issue by james-d-mitchell** [gap-packages/Digraphs#17]
Originally reported by: **Christopher Jefferson (Bitbucket: [ChrisJefferson](http://bitbucket.org/ChrisJefferson), GitHub: [ChrisJefferson](http://github.com/ChrisJefferson))**

---

The following shows a practical example.

```
gap> d := Digraph([ [2], [3], [1,1] ]);
<multidigraph with 3 vertices, 4 edges>
gap> Print(OnDigraphs(d, PermList([2,3,1])));
Digraph( [ [ 2, 2 ], [ 3 ], [ 1 ] ] )
gap> Print(OnDigraphs(d, Transformation([2,3,1])));
Digraph( [ [ 2 ], [ 3 ], [ 1 ] ] )
```

I imagine that multidigraphs should repeat edges with transformation?

---
- Bitbucket: https://bitbucket.org/james-d-mitchell/digraphs/issue/17

**Comment by wilfwilson** [comment]
Fixed by PR #36.
