### ISSUE TITLE
Digraphs doesn't work in GAP master branch

### ISSUE THREAD

**Issue by wilfwilson** [gap-packages/Digraphs#172]
This is because GAP's `COUNT_TRUES_BLOCK` has been moved, so we are not including it any more. (See https://github.com/gap-system/gap/issues/3312). However, it has been moved to a header called `bits_intern.h`, which implies that the GAP developers intend for this to be an internal function. So perhaps the correct solution is not to simply include `bits_intern.h`. We'll see!

**Comment by james-d-mitchell** [comment]
Is this now resolved?? @wilfwilson

**Comment by wilfwilson** [comment]
Resolved by GAP PRs https://github.com/gap-system/gap/pull/3317 and https://github.com/gap-system/gap/pull/3318
