### ISSUE TITLE
Adjacents lists should be sets where possible

### ISSUE THREAD

**Issue by james-d-mitchell** [gap-packages/Digraphs#18]
Originally reported by: **Christopher Jefferson (Bitbucket: [ChrisJefferson](http://bitbucket.org/ChrisJefferson), GitHub: [ChrisJefferson](http://github.com/ChrisJefferson))**

---

While digraphs doesn't require that the neighbours of a vertex be ordered, they often will be in practice. For example:

```
d := Digraph([2,3],[1,3],[1,2])
```

however, because GAP doesn't know these things are sets, operations like `IsDigraphEdge`, which turn into `v in OutNeighboursOfVertex(digraph,u)` have to do a linear search through the neighbours, when they could do a binary search through an ordered list.

There are other places where the sortedness could be used (= and < on graphs for example), but to start it would be useful to just get GAP to do what it's already good at.

The easiest way to make this happen would be to call `IsSet` on each member of adjacency list, which makes GAP scan the lists, and mark the as an ordered list if they are. Calling `IsSet` on a list should make no practical different (you can still edit it, extend it, etc.), but GAP will remember it is a set (until it is altered).

I don't think (but you might disagree!) that doing these `IsSet` calls during construction would add that much time (it's an O(n) linear scan), but if it is too expensive, you could always add a method to do this. I'm already using one myself:

```
MakeSety := function(d)
    List(DigraphVertices(d), x -> IsSet(OutNeighboursOfVertex(d, x)));
end;
```

An example that this is useful.

```
gap> d := CompleteDigraph(1000);
gap> Sum([1..1000], x-> Length(Filtered([1..1000], y -> IsDigraphEdge(d, x, y))));
999000
gap> time;
1078
gap> MakeSety(d);
gap> time;
2
gap> Sum([1..1000], x-> Length(Filtered([1..1000], y -> IsDigraphEdge(d, x, y))));
999000
gap> time;
712
```

---
- Bitbucket: https://bitbucket.org/james-d-mitchell/digraphs/issue/18

**Comment by wilfwilson** [comment]
This was resolved by commit 861222c
