### ISSUE TITLE
Automorphims of edge colored graphs

### ISSUE THREAD

**Issue by videlec** [gap-packages/Digraphs#183]
I would be interested in computing automorphism group of edge colored graph. One possibly straightforward way would be to have an extra optional argument `EdgeColoring` to the automorphism routine.

(aim: use it for the [GaloisGroups](https://github.com/gap-packages/GaloisGroups/) package)

**Comment by james-d-mitchell** [comment]
@flsmith and @videlec are doing this just now.

**Comment by videlec** [comment]
@flsmith  with your last commit, the following does work
```
gap> D := Digraph([[2],[1]]);
gap> AutomorphismGroup(D, fail, [[1],[2]]);
Group(())
```
but not these ones
```
gap> AutomorphismGroup(D, fail, fail);
gap> AutomorphismGroup(D, [1,2], fail);
```
Should they be expected to work?

**Comment by videlec** [comment]
It would be wonderful to get this finished. I thought we were mostly done after our work in Halle. Any help needed?

**Comment by flsmith** [comment]
I realised recently that the method we implemented is simply invalid for multidigraphs (even when the edge colours are unique) and haven't found a solution yet. Can you remind me whether you need that?

**Comment by videlec** [comment]
One way to do it is to create a new colour for each set of colours. Then you can replace multiple edges by a single edge. If you map multiset of colours you can also take care of non-uniquely colored multiple edges.
