### ISSUE TITLE
configure option to use external bliss and planarity

### ISSUE THREAD

**Issue by isuruf** [gap-packages/Digraphs#205]

**Comment by james-d-mitchell** [comment]
For reference, the suggestion is to do something like what was done for Semigroups in:


https://github.com/gap-packages/Semigroups/pull/590
https://github.com/gap-packages/Semigroups/pull/593
https://github.com/gap-packages/Semigroups/pull/595

**Comment by james-d-mitchell** [comment]
Hmm, so, one problem is that the released version of bliss had some bugs in it, which we resolved in the version that's included with Digraphs. So, if we use the system bliss these problems will still exist, I think the same was true for libplanarity (although to a lesser extent). I'm not sure how to resolve this as neither bliss nor libplanarity have public repos where issues can be reported, as far as I am aware.

**Comment by isuruf** [comment]
We can patch bliss and libplanarity with the fixes here for the system version. (extern issue is already fixed with planarity system copy I'm using)

**Comment by james-d-mitchell** [comment]
Ok awesome, I'll work on a PR to use the system planarity just now.

**Comment by james-d-mitchell** [comment]
@isuruf if you make a bliss conda feedstock, then I can apply the patch we used in Digraphs.

**Comment by isuruf** [comment]
Fixed by https://github.com/gap-packages/Digraphs/pull/207. Thanks @james-d-mitchell

**Comment by isuruf** [comment]
#207 only fixes planarity.

**Comment by dimpase** [comment]
We should merge bliss fixes from https://github.com/mkoeppe/bliss and the ones here, to create a "canonical" version.

**Comment by isuruf** [comment]
@james-d-mitchell, we also have https://github.com/conda-forge/bliss-feedstock which uses  https://github.com/mkoeppe/bliss

**Comment by james-d-mitchell** [comment]
Agreed @dimpase it'd be good to have a merged version of bliss with all existing fixes included.

**Comment by wilfwilson** [comment]
@isuruf added the `--with-external-bliss` option in #225, which was included in the v1.0.0 release, so I'll close this now.
