### ISSUE TITLE
Implement digraph products and related operations

### ISSUE THREAD

**Issue by reiniscirpons** [gap-packages/Digraphs#226]
There are many notions of digraph product. Furthermore, there is a notion of primality and unique factorization wrt these products, and there are efficient algorithms for computing some of them (see article at the end for a full exposition).

I think it would be nice to implement:
- `DigraphCartesianProduct(G1, G2, ...)` - for digraphs compute the Cartesian product of all of them.
- `DigraphDirectProduct(G1, G2, ...)` - for digraphs compute the Direct product of all of them.
- `IsDigraphCartesianProductPrime(G)` - for a digraph decide whether its prime wrt the Cartesian product.
- `IsDigraphDirectProductPrime(G)` - for a digraph decide whether its prime wrt the Direct product.
- `DigraphCartesianSkeleton(G)` - for a digraph, compute its Cartesian skeleton (this is useful in direct product factorization)
- `DigraphCartesianPrimeFactorization(G)` - for a digraph, compute its prime factors wrt the Cartesian product.
- `DigraphDirectPrimeFactorization(G)` - for a digraph, compute its prime factors wrt the Direct product.

-----
Some theory:
For digraphs `G` and `H` there are multiple possible ways of defining a product digraph. Two of the more important ones are:

1.  Cartesian product `G ☐ H`. The set of vertices is `V(G) x V(H)`, there is an edge between `(x, x')` and `(y, y')` iff either `(x, y) ∈ E(G)` and `x' = y'` or `x = y` and `(x',y') ∈ E(H)`. 

2. Direct product `G x H`. The set of vertices is `V(G) x V(H)`, there is an edge between `(x, x')` and `(y, y')` iff `(x, y) ∈ E(G)` and `(x',y') ∈ E(H)`. 

Here `V(G), E(G)` is the set of edges and vertices of `G` respectively.

For more information see
[Hammack R.H. (2018) Digraphs Products. In: Bang-Jensen J., Gutin G. (eds) Classes of Directed Graphs. Springer Monographs in Mathematics. Springer, Cham](https://link.springer.com/chapter/10.1007/978-3-319-71840-8_10)

**Comment by james-d-mitchell** [comment]
Good idea @reiniscirpons! Any possibility of a PR in this direction??
