### ISSUE TITLE
DigraphDisjointUnion vertex labels for mutable digraphs

### ISSUE THREAD

**Issue by MTWhyte** [gap-packages/Digraphs#227]
On the current master, I get some unexpected behaviour when I apply `DigraphDisjointUnion` to a mutable digraph.

~~~
gap> D := CycleDigraph(IsMutable, 2);
<mutable digraph with 2 vertices, 2 edges>
gap> DigraphVertexLabels(D);
[ 1, 2 ]
gap> DigraphDisjointUnion(D, D);
<mutable digraph with 4 vertices, 4 edges>
gap> D;
<mutable digraph with 4 vertices, 4 edges>
gap> DigraphVertexLabels(D);
[ 1, 2 ]
~~~

where I'd expected to see `[ 1 .. 4 ]` returned, instead of `[ 1, 2 ]`. For an immutable digraph, what I'd expected is returned, as in
~~~
gap> D := CycleDigraph(2);
<immutable digraph with 2 vertices, 2 edges>
gap> DigraphVertexLabels(D);
[ 1, 2 ]
gap> DigraphVertexLabels(DigraphDisjointUnion(D, D));
[ 1 .. 4 ]
~~~

This unexpected behaviour only happens when `SetDigraphVertexLabels` is called on the mutable digraph before `DigraphDisjointUnion`, as in

~~~
gap> D := CycleDigraph(IsMutable, 2);
<mutable digraph with 2 vertices, 2 edges>
gap> DigraphDisjointUnion(D, D);
<mutable digraph with 4 vertices, 4 edges>
gap> DigraphVertexLabels(D);
[ 1 .. 4 ]
~~~

This has implications for using functions like `InducedSubdigraph` (in fact, this is how I found it). I get

~~~
gap> D := CycleDigraph(IsMutable, 2);
<mutable digraph with 2 vertices, 2 edges>
gap> DigraphVertexLabels(D);
[ 1, 2 ]
gap> DigraphDisjointUnion(D, D);
<mutable digraph with 4 vertices, 4 edges>
gap> InducedSubdigraph(D, [3, 4]);
Error, List Elements: <list>[3] must have an assigned value in
  SetDigraphVertexLabels( D, old_labels{list}
 ); at /Users/murraywhyte/gap/pkg/Digraphs/gap/oper.gi:831 called from
<function "unknown">( <arguments> )
 called from read-eval loop at *stdin*:54
type 'quit;' to quit to outer loop
~~~

I have a fix for this behaviour for `DigraphDisjointUnion` already, which just runs `SetDigraphVertexLabels(D, DigraphVertices(D))` before returning `D`. If it's agreed that what I think is unexpected behaviour really is, and that this is the best solution to it, I'm ready to push. This approach loses the prior vertex labelling of the arguments to `DigraphDisjointUnion`, but I think that happens in any case for immutable digraphs.

Looking in to how the `DigraphDisjointUnion` method works, it seems to be related to how editing the outneighbours of a mutable digraph `D` doesn't change the vertex labels, if the `D!.vertexlabels` list already exists, as in

~~~
gap> D := CycleDigraph(IsMutable, 2);
<mutable digraph with 2 vertices, 2 edges>
gap> DigraphVertexLabels(D);
[ 1, 2 ]
gap> A := D!.OutNeighbours;
[ [ 2 ], [ 1 ] ]
gap> A[3] := [2];
[ 2 ]
gap> D;
<mutable digraph with 3 vertices, 3 edges>
gap> DigraphVertexLabels(D);
[ 1, 2 ]
~~~

Perhaps there are other functions which work similarly to `DigraphDisjointUnion` - the vertex labelling for mutable digraphs would still behave similarly for those functions, and so this might be better addressed by changing the behaviour of the `D!.OutNeighbours` list for mutable digraphs to alter the `D!.vertexlabels` list too? I'm not really sure what all the advantages and disadvantages of this would be, though, and if it's useful in some cases that altering `D!.OutNeighbours` leaves the vertex labelling alone?

**Comment by wilfwilson** [comment]
Thanks for spotting this and dealing with this. We shouldn't worry about the fact that accessing `D!.OutNeighbours` and manipulating it directly can leave digraphs in inconsistent states - this is not a user-facing feature, we're the only people who should be using it. And when we use it in methods in this package, we should just be careful.
