### ISSUE TITLE
PrintString should use the digraph-to-string functions from io.gi

### ISSUE THREAD

**Issue by wilfwilson** [gap-packages/Digraphs#232]
I think this would lead to much shorter output than using the out-neighbours. This would require the string-to-digraph functions being adjusted to take `IsMutableDigraph`/`IsImmutableDigraph` as an optional first argument.

I don't see this as a priority, in particular, it can wait until after 1.0.

**Comment by james-d-mitchell** [comment]
I see your point, but I'm not sure this is really desirable, given that the output is not human readable.

**Comment by wilfwilson** [comment]
Good point. I'll close, always happy to save us some work 😉

**Comment by james-d-mitchell** [comment]
It'd still be useful to have a method of printing the "shortest" string representing the digraph, I'm not sure if there's an issue for that already?

**Comment by wilfwilson** [comment]
I don't think so. Perhaps it's relevant for #47?

**Comment by james-d-mitchell** [comment]
Yeah, I think that's what I was thinking of. Maybe we could make a new issue for that?
