### ISSUE TITLE
Have a tool for producing the smallest string representing a digraph

### ISSUE THREAD

**Issue by wilfwilson** [gap-packages/Digraphs#233]
This could be one of the encoding formats, or via the list of out-neighbours, or via source and range, and so on...

I don't think it matters if it's actually the exact smallest option that we have for representing the digraph, only that it gets reasonably close.

**Comment by james-d-mitchell** [comment]
I think @MTWhyte is working on this.

**Comment by wilfwilson** [comment]
Great. I added a tiny bit more info to the issue description.
