### ISSUE TITLE
Using cloned repo.

### ISSUE THREAD

**Issue by mpizana** [gap-packages/Digraphs#24]
I have successfully installed and loaded Digraphs 0.4.2 which came bundled with GAP4r8.

But prefer to clone its github repository so I can test different versions and upgrade easily. But I have not been able to install any version from the git repository. When I clone the repository there is no "configure" file. This happens in all testes branches (master, stable-0.5, stable-0.6). Any help here?

**Comment by james-d-mitchell** [comment]
The build files `configure` and `Makefile` are auto-generated and not part of the git repo. You can auto-generate them by running `./autogen.sh` in the Digraphs directory (the script is part of the repo). For this you'll require the command line tools `autoconf` and `automake`, which on Mac OS X (for example) can be installed using [homebrew](brew.sh)

**Comment by mpizana** [comment]
Thanks, I use Mac ports. Automake and autoconf installed, but script complaints about dnl being not found:

```
$ sudo port install autoconf
--->  Computing dependencies for autoconf
--->  Cleaning autoconf
--->  Scanning binaries for linking errors
--->  No broken files found.                             
Miguels-iMac:digraphs map$ sudo port install automake
--->  Cleaning automake
--->  Scanning binaries for linking errors
--->  No broken files found.
$ ./configure.ac
./configure.ac: line 8: dnl: command not found
./configure.ac: line 9: dnl: command not found
./configure.ac: line 10: dnl: command not found
./configure.ac: line 11: syntax error near unexpected token `[2.68]'
./configure.ac: line 11: `AC_PREREQ([2.68])'
$
```

**Comment by mpizana** [comment]
Thanks, it worked well in Mac.

Ubuntu complains about LIBTOOL:

```
$ sudo ./autogen.sh 
Makefile.am:12: error: Libtool library used but 'LIBTOOL' is undefined
Makefile.am:12:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
Makefile.am:12:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
Makefile.am:12:   If 'LT_INIT' is in 'configure.ac', make sure
Makefile.am:12:   its definition is in aclocal's search path.
autoreconf: automake failed with exit status: 1
$
```

**Comment by mpizana** [comment]
"configure" does get generated, but it complains when executed:

```
$sudo ./configure
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
-- many more lines here --
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
./configure: line 4528: syntax error near unexpected token `2.4.2'
./configure: line 4528: `LT_PREREQ(2.4.2)'
$
```

**Comment by mpizana** [comment]
Ubuntu version used: 

```
$ uname -a
Linux xaman 3.13.0-93-generic #140-Ubuntu SMP Mon Jul 18 21:21:05 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by james-d-mitchell** [comment]
Ah, sorry I forgot you need `libtool` too, just do `sudo apt-get install libtool` in ubuntu, and then run `./autogen.sh` again. 

Just to mention that, of course, none of this is necessary in the release version.

**Comment by mpizana** [comment]
Still not working:

```
$ sudo apt-get install libtool
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libtool is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 26 not upgraded.
$ sudo git checkout
Your branch is up-to-date with 'origin/stable-0.5'.
$ sudo ./autogen.sh 
Makefile.am:12: error: Libtool library used but 'LIBTOOL' is undefined
Makefile.am:12:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
Makefile.am:12:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
Makefile.am:12:   If 'LT_INIT' is in 'configure.ac', make sure
Makefile.am:12:   its definition is in aclocal's search path.
autoreconf: automake failed with exit status: 1
$ sudo ./configure 
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
-- many more lines here --
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
./configure: line 4528: syntax error near unexpected token `2.4.2'
./configure: line 4528: `LT_PREREQ(2.4.2)'
$
```

Yes, I understand that the release version it is much easier to use. Thanks for all the help here.

**Comment by james-d-mitchell** [comment]
Try doing:

     make clean
    ./autogen.sh

and only if it works with no error do `./configure ; make -j4`

**Comment by james-d-mitchell** [comment]
and it that doesn't work try `sudo apt-get install build-essential`, then repeat the steps in my previous comment. I hope it works, if not please let me know!

**Comment by mpizana** [comment]
`make clean` can not be issued since `Makefile` has not been created. But I deleted all files not listed in `git ls-tree --name-only HEAD`, namely `rm -fr configure autom4te.cache cnf config.log` and tried again, and same problem happened. Then I deleted all the directory and cloned the repository anew and the same happened. Also, it does not seem that `build-essential` is the problem:

```
$sudo apt-get install build-essential
Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version.
build-essential set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 26 not upgraded.
$ sudo ./autogen.sh 
configure.ac:28: installing 'cnf/ar-lib'
configure.ac:28: installing 'cnf/compile'
configure.ac:21: installing 'cnf/config.guess'
configure.ac:21: installing 'cnf/config.sub'
configure.ac:26: installing 'cnf/install-sh'
configure.ac:26: installing 'cnf/missing'
Makefile.am:12: error: Libtool library used but 'LIBTOOL' is undefined
Makefile.am:12:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
Makefile.am:12:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
Makefile.am:12:   If 'LT_INIT' is in 'configure.ac', make sure
Makefile.am:12:   its definition is in aclocal's search path.
Makefile.am: installing 'cnf/depcomp'
autoreconf: automake failed with exit status: 1
$
```

Or perhaps "build-essential set to manually installed" is a bad thing?

**Comment by james-d-mitchell** [comment]
Hmm, I get

    jdm@ubuntu:~/gap/pkg/Digraphs$ ./autogen.sh
    libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `cnf'.
    libtoolize: copying file `cnf/ltmain.sh'
    libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
    libtoolize: copying file `m4/libtool.m4'
    libtoolize: copying file `m4/ltoptions.m4'
    libtoolize: copying file `m4/ltsugar.m4'
    libtoolize: copying file `m4/ltversion.m4'
    libtoolize: copying file `m4/lt~obsolete.m4'
    configure.ac:28: installing 'cnf/ar-lib'
    configure.ac:28: installing 'cnf/compile'
    configure.ac:21: installing 'cnf/config.guess'
    configure.ac:21: installing 'cnf/config.sub'
    configure.ac:26: installing 'cnf/install-sh'
    configure.ac:26: installing 'cnf/missing'
    Makefile.am: installing 'cnf/depcomp'

and everything works ok. I'm not sure what to advise further, perhaps @mtorpey can think of something??

**Comment by james-d-mitchell** [comment]
The set up is:

    host-triplet:	x86_64-pc-linux-gnu
    shell:		/bin/bash
    compiler:		gcc
    compiler flags:		-Wall -g -O2
    linker:		/usr/bin/ld -m elf_x86_64 (gnu? yes)
    libtool:	(GNU libtool) 2.4.2 Debian-2.4.2-1.7ubuntu1
    automake:	automake (GNU automake) 1.14.1
    autoconf:	autoconf (GNU Autoconf) 2.69

**Comment by mpizana** [comment]
I understand. Tomorrow I will try more actively.

**Comment by mpizana** [comment]
It works now! We were so close last time, we just missed to execute `libtoolize` (in the directory digraphs). So it seems that the procedure should be:

```
libtoolize
./autogen.sh
./configure
make
```

Perhaps it could be a good idea to add this in a new section to the README.md for people willing to use the repository directly?

Thanks a lot for all the help.

**Comment by james-d-mitchell** [comment]
Great! We will make a wiki page with the relevant information on it. 

Can we close the issue?

**Comment by mpizana** [comment]
Sure!

**Comment by fingolfin** [comment]
Actually, autoreconf (which is what autogen.sh run) already is supposed tomautomatically run libtoolize. And sp far, it always did for me, on s wide variety of systems. So this is weird, and it would be good to get to the bottom of ot.

Also, I wonder why you use sudo to run all the scripts. That seems risky -- but perhaps you are installing the package system wide, and are doing it for that reason?

**Comment by mpizana** [comment]
Yes I was installing Digraphs system wide. Still, it is indeed risky to run scripts as root with unknown content (for me)... I should rather make myself belong to some group with write privileges on the pertinent directories. Maybe next time.

Is there a test you would like to do on my system to get to the bottom of it?
