### ISSUE TITLE
strange mutablity in clique outputs

### ISSUE THREAD

**Issue by le27** [gap-packages/Digraphs#240]
Some of the clique functions in the master branch, such as DigraphMaximalCliques, return a mutable list of immutable lists, this is a bit strange.

For example:
```gap
gap> D := Digraph(IsMutableDigraph,
> [[2, 3], [1, 3], [1, 2, 4], [3, 5, 6], [4, 6], [4, 5]]);;
gap> cliques := DigraphMaximalCliques(D);
[ [ 1, 2, 3 ], [ 4, 5, 6 ], [ 3, 4 ] ]
gap> IsMutable(cliques);
true
gap> IsMutable(cliques[1]);
false
```
the list [ [ 1, 2, 3 ], [ 4, 5, 6 ], [ 3, 4 ] ] is mutable but the lists [ 1, 2, 3 ], [ 4, 5, 6 ] and [ 3, 4 ] are immutable.

**Comment by wilfwilson** [comment]
Thanks for the report.
