### ISSUE TITLE
Mutable DigraphFromDigraph6String

### ISSUE THREAD

**Issue by le27** [gap-packages/Digraphs#245]
In the master branch the function DigraphFromDigraph6String when asked to return a Mutable digraph will return false instead of a digraph e.g:
```
gap> digraph := DigraphFromDigraph6String("&IGO??S?`?_@?a?CK?O");     
<immutable digraph with 10 vertices, 14 edges>
gap> digraph := DigraphFromDigraph6String(IsMutableDigraph,         
>                                         "&IGO??S?`?_@?a?CK?O");
false
```

**Comment by wilfwilson** [comment]
This is simply because specifying mutability for the functions in `gap/io.g*` has not been implemented, as far as I can tell.

The (undocumented) 2-argument versions of functions like (say) `DigraphFromDigraph6String` have a different purpose, it seems.

**Comment by wilfwilson** [comment]
The current 2-argument versions of these functions should probably be `DIGRAPHS_` or `NC` functions, they definitely shouldn't be user-facing.

That way we can implement proper two-argument versions where the first optional argument is `IsMutableDigraph` or `IsImmutableDigraph`.

**Comment by james-d-mitchell** [comment]
I couldn't remember, I agree, the above behaviour is weird, and unexpected.

**Comment by james-d-mitchell** [comment]
Wait, I don't think the current 2-arg versions should be `NC` or `DIGRAPHS_` since they are intended to allow users to pass their own decoder or encoder functions

**Comment by james-d-mitchell** [comment]
There's a TODO:

~~~~
#  TODO Document the optional (e.g.) `IsMutableDigraph` first argument for
#       many of these operations.
~~~~
in the `io.gd` file, but there aren't any `IsMutableDigraph` methods, so what's that about

**Comment by james-d-mitchell** [comment]
No wait I wrote too quickly, I will look at this more closely

**Comment by wilfwilson** [comment]
> Wait, I don't think the current 2-arg versions should be `NC` or `DIGRAPHS_` since they are intended to allow users to pass their own decoder or encoder functions

Yes, we should work out a way to preserve this ability. But for things like `DigraphFromDigraph6String`/`DigraphFromGraph6String/...`, there is no need for a user to specify a custom decoder  - that's not what's going on with its optional first argument. The decoder required is implicit in the name of the function.

On the whole, I don't mind what we do here, I won't be terribly upset if making these things support `IsMutableDigraph` and `IsImmutableDigraph` waits until after 1.0.

**Comment by james-d-mitchell** [comment]
I agree, I wrote that too quickly, I'm going to try to resolve this issue so that `false` is not returned above.
