### ISSUE TITLE
Allow passing a filter (such as IsMutableDigraph) to DigraphFromDigraph6String and friends

### ISSUE THREAD

**Issue by james-d-mitchell** [gap-packages/Digraphs#250]
I think the title says it all, at present `DigraphFromDigraph6String` always returns an immutable digraph, but could be modified to return either a mutable or an immutable digraph, similar to, for example, `Digraph`.

**Comment by MTWhyte** [comment]
I will do this.

**Comment by wilfwilson** [comment]
This was released in v1.0.0.
