### ISSUE TITLE
Incorrect storing of GeneratorsOfEndomorphismMonoid

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-packages/Digraphs#251]
GeneratorsOfEndomorphismMonoid stores created generators as an attribute, even when a colouring was given. See for example, where the second and last lines should be the same.

For information, this was tracked down (after I realised I was getting weird answers from Digraphs) using `SetInfoLevel(InfoAttributes, 5)`, which (in the head of GAP) shows when you try to set an attribute to a different value and the assignment fails (which isn't necessarily an error, but is suspicious). 

```
gap> gr := CompleteDigraph(5);
<digraph with 5 vertices, 20 edges>
gap> GeneratorsOfEndomorphismMonoid(gr);
[ Transformation( [ 1, 2, 3, 5, 4 ] ), Transformation( [ 1, 2, 4, 3 ] ), Transformation( [ 1, 3, 2 ] ), Transformation( [ 2, 1 ] ), IdentityTransformation ]
gap> gr := CompleteDigraph(5);
<digraph with 5 vertices, 20 edges>
gap> GeneratorsOfEndomorphismMonoid(gr, [1, 1, 1, 2, 3]);
[ Transformation( [ 1, 3, 2 ] ), Transformation( [ 2, 1 ] ), IdentityTransformation ]
gap> GeneratorsOfEndomorphismMonoid(gr);
[ Transformation( [ 1, 3, 2 ] ), Transformation( [ 2, 1 ] ), IdentityTransformation ]
```

**Comment by wilfwilson** [comment]
Thanks for the report @ChrisJefferson
