### ISSUE TITLE
Remove -march=native and -mpopcnt if not supported

### ISSUE THREAD

**Issue by isuruf** [gap-packages/Digraphs#293]
Also please add an option to remove them even if supported for binary distributions like conda.

**Comment by james-d-mitchell** [comment]
Happy to add this, I made a PR for Semigroups: 

https://github.com/gap-packages/Semigroups/pull/651

If you agree that this fixes the issue in Semigroups, then I'll make a similar PR here.

**Comment by james-d-mitchell** [comment]
Resolved in v1.1.2
