### ISSUE TITLE
Much slower Travis job when without intrinsics

### ISSUE THREAD

**Issue by wilfwilson** [gap-packages/Digraphs#316]
Merging PR #296 caused the second Travis job (64-bit, GAP stable-4.11, external planarity and bliss, and now without intrinsics) to more than double its required time, from about 12 minutes ([example](https://travis-ci.org/github/gap-packages/Digraphs/jobs/656949829)) to 28 minutes ([example](https://travis-ci.org/github/gap-packages/Digraphs/jobs/657252460)).

Was this expected? If not, it's probably worth looking into. But if it was expected, as I presume, then I suggest that we should either not test `--without-intrinsics` at all, or at least move that option to a less demanding job (such as the one without `NautyTracesInterface` installed) so that it completes in a reasonable time.

Any opinions?

**Comment by james-d-mitchell** [comment]
Is it maybe worth just not running the extreme tests in that job? Is that what's taking the time?

**Comment by wilfwilson** [comment]
Yeah, specifically it's line 79 of `extreme/grahom.tst` that takes up most the time of that job (and the other jobs that run the extreme tests).

And yes, I think that's a reasonable compromise. I'll make such a PR.

**Comment by wilfwilson** [comment]
Resolved by #317.
