### ISSUE TITLE
Error compiling digraphs package on windows 7

### ISSUE THREAD

**Issue by khughes1** [gap-packages/Digraphs#39]
I am having problems compiling the GAP package digraphs.  
I am running Windows 7 Professional SP1 and GAP 4.8.6.
![gap](https://cloud.githubusercontent.com/assets/25080787/21892842/96d6284c-d8d0-11e6-856a-457f5639b90d.png)

I have read the instructions https://www.gap-system.org/Manuals/pkg/digraphs-0.5.2/doc/manual.pdf
In order to run the ./configure and make I downloaded MinGW. 
Using MinGW I navigated to the /pkg/digraphs-0.5.2 folder and then typed ./configure.
This I think worked ok although I am not sure. It returned no errors.
Then when  I typed make I got the following

![untitled](https://cloud.githubusercontent.com/assets/25080787/21892691/ef3275fa-d8cf-11e6-93be-23ef41d2f29e.png)

I did a google search for unknown type name 'sigjmp_buf' but I did not see anything useful.

Does the screen shot above (the one of GAP running) suggest that I am using Cygwin to run GAP 
Architecture: i686-pc-cygwin-gcc-default32
and is this a problem when using MinGW to configure and make the digraphs package.

I have no idea as to what to do now. Any help would be appreciated.

Best regards,

Kieran.

Regards,

**Comment by james-d-mitchell** [comment]
@ChrisJefferson you wouldn't have any idea what's going on here would you?

**Comment by ChrisJefferson** [comment]
You can't use mingw, you must use cygwin.

I would recommend compiling gap from scratch when you compile digraphs, to ensure gap and digraphs are compiled with the same version of cygwin.

**Comment by alex-konovalov** [comment]
Perhaps we should try to add Digraphs to the list of packages with kernel modules that we build for the .exe GAP installer for Windows. I've created a reminder for myself in https://github.com/gap-system/gap-distribution/issues/21

**Comment by khughes1** [comment]
Thank you Chris and Alex for replying.
I have put in a request to get Cygwin installed on my machine and I will retry. I will post how I get on although the request make take some time.

**Comment by khughes1** [comment]
I have some related questions.
I run Sage with Virtual box. Would I be better to try to compile GAP from a virtual box session or maybe from a separate machine that runs Linux or something similar. 
Are these issues windows specific? I guess I will still have to compile GAP and the packages but maybe this is easier when not using windows. 

Update : I have installed Cygwin but I can't compile GAP using it. I think that I did not include all the required cygwin packages (there were a lot to choose from) as I get the following message
![image](https://cloud.githubusercontent.com/assets/25080787/21934110/1bc0194e-d9a0-11e6-9968-fbeb25b7bd18.png)
Is there a list of the Cygwin packages required for a GAP installation somewhere I found 
https://www.gap-system.org/Download/tools.html

which would indicate 
a C compiler (preferably gcc 4.2 or higher), a C++ compiler, and the m4 macro processor; 
I thought that I did include these packages but maybe I didn't. Is there an easy way to check?

This is a lot of questions but any tips would be great.

regards,

Kieran.

**Comment by ChrisJefferson** [comment]
Try typing `gcc` to see if you installed a C compiler -- I suspect you didn't. Look for `gcc` and `g++`, and also `make` and `m4`.

We really should have a page which more accurately describes how to build gap on cygwin.

**Comment by james-d-mitchell** [comment]
@khughes1 is this now resolved? 

Just to mention: this is a windows isssue, if you were using Digraphs on Mac OS X or linux, then there are no issues (at least as far as I know).

**Comment by ChrisJefferson** [comment]
@james-d-mitchell : You would get exactly the same problem on mac or linux if you installed a dodgy compiler, it's just much less common for anyone to run different compilers, whereas on Windows you can choose between cygwin, mingw and visual studio (and only cygwin works)

**Comment by james-d-mitchell** [comment]
I'm going to mark this as resolved, unless anyone objects??
