### ISSUE TITLE
DigraphGroup doesn't record group Size

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-packages/Digraphs#40]
DigraphGroup should be able to extract from bliss the size of the found group, and attach it to the group. This information would be very useful, as I have a group where DigraphGroup took 3 seconds, but Size is still not finished, and has taken over 10 minutes.

**Comment by james-d-mitchell** [comment]
This is a good idea. 

@ChrisJefferson Do you have any idea how to get the size from bliss? On very quick inspection, I can't seem to find a method which returns the size, and in `defs.hh` it seems to suggest that `gmp` is required to do this.

**Comment by ChrisJefferson** [comment]
@saadattieh 's alternative implementation is now complete. The main useful features it will bring are:

1) Canonical image works properly with partitions (fixes #19)
2) DigraphGroup will return a group with the known Size, and also a valid stabilizer chain (if wanted.. I suspect it will be wanted)
3) Faster, and with (optional) parallelisation.

I suggest to start with we plug both systems in (partly for comparision), then later bliss can be removed if the replacement is always better. We could also just have a "big bang" were bliss is replaced.

**Comment by james-d-mitchell** [comment]
This sounds really good. I'm happy with either a big bang or a both systems, the latter might be a bit more complicated than necessary. We can always compare the development version with the release version. Do you want one of us to do this or will you and @saadattieh?

**Comment by wilfwilson** [comment]
@ChrisJefferson What's the status/location of @SaadAttieh's implementation? Do you still recommend integrating it into Digraphs?

**Comment by james-d-mitchell** [comment]
I was wondering about this recently too.

**Comment by ChrisJefferson** [comment]
Hi!

Sorry, going back to an old, old PR.

As this is a useful feature, and hungry seems to have gotten stuck on some subtle bugs we are probably never going to fix, I've decided to just add this to Bliss instead. I have hacked up the feature in bliss, it would be useful to have someone to work with me on the digraphs side of things.
