### ISSUE TITLE
Travis problems

### ISSUE THREAD

**Issue by wilfwilson** [gap-packages/Digraphs#41]
The Travis tests are currently failing. This not because of the Digraphs package itself, since Travis is not managing to properly load GAP in the first instance.

I'm not an expert on Travis, so I'm not sure whether the problem is our fault or Travis's fault (or something else). However I thought I should record the failure somewhere, since as far as I'm aware the tests and manual examples are running fine in the package.

**Comment by wilfwilson** [comment]
...perhaps @mtorpey could investigate?

**Comment by ChrisJefferson** [comment]
gap-system.org is only accessable via https nowadays, so I think your  travis-test.sh script needs updating with https.

**Comment by wilfwilson** [comment]
Thanks Chris. I'll make some changes.

**Comment by wilfwilson** [comment]
That was indeed the problem @ChrisJefferson, thank you.
