### ISSUE TITLE
IsSubdigraph and multiple edges

### ISSUE THREAD

**Issue by wilfwilson** [gap-packages/Digraphs#46]
There is a function at the top of `oper.gi` called `IsSubdigraph`. It has the following documentation:
```
If  super  and  sub are digraphs with the same number of vertices, then this
operation returns true if all the edges of sub are edges in super, and false
otherwise.
```
Apart from this, `IsSubdigraph` is not used or mentioned anywhere else in the package. In particular, there is no code coverage, so I thought I'd write some, but I encountered trouble.

I think this documentation is fine if `super` and `sub` have no multiple edges. However, I don't think it is specific enough for the cases when there are multiple edges. In my opinion, talking about digraphs in general, which may or may not have multiple edges, the multiplicity of each edge of the subdigraph should be less than or equal to the multiplicity of the edge in the super digraph.

In particular, the method does this (after checking that the numbers of vertices are equal):
```
  return ForAll(DigraphVertices(super), i ->
                IsSubset(OutNeighboursOfVertex(super, i),
                         OutNeighboursOfVertex(sub, i)));
```
So (as documented) it is simply checking that for every edge `i->j` in `sub` there is an edge `i->j` in `super`. When `sub` is a multidigraph, this leads to behaviour that I think is weird:
```
gap> super := Digraph([[2], []]);;
gap> sub := Digraph([[2, 2], []]);;
gap> IsSubdigraph(super, sub);
true
gap> IsSubdigraph(sub, super);
true
gap> super = sub;
false
```
Surely `sub` should be the "larger" digraph in this case, and surely distinct digraphs shouldn't be subdigraphs of each other!

Does anyone object to me changing the documentation, and the code, so that `IsSubdigraph` does take account of multiplicities?

**Comment by james-d-mitchell** [comment]
Sounds good to me.

**Comment by wilfwilson** [comment]
I made this change in commit 852e0e8.
