### ISSUE TITLE
DigraphTopologicalSort causes seg fault

### ISSUE THREAD

**Issue by wilfwilson** [gap-packages/Digraphs#55]
Similar to the bug in `IsAntisymmatricDigraph` #52, I have found a bug in `DigraphTopologicalSort`, caused by the function `FuncDIGRAPH_TOPO_SORT` assuming that it is given a PLIST of PLISTs. Current behaviour:
```
gap> gr := Digraph([[1 .. 4], [2, 4], [3 ,4], [4]]);
<digraph with 4 vertices, 9 edges>
gap> DigraphTopologicalSort(gr);
Segmentation fault: 11
```
Expected output:
```
gap> gr := Digraph([[1 .. 4], [2, 4], [3 ,4], [4]]);
<digraph with 4 vertices, 9 edges>
gap> DigraphTopologicalSort(gr);
[ 4, 2, 3, 1 ]
```
I've identified the problem, it's the same kind of issue as caused Issue #52. I'll make a PR to fix it, but I thought it would make it easier to keep track of these things for the release and for the tests if I also create an issue.

**Comment by james-d-mitchell** [comment]
Resolved by PR #56
