### ISSUE TITLE
autogen.sh not mentioned in README.md

### ISSUE THREAD

**Issue by cdwensley** [gap-packages/Digraphs#68]
Just forked Digraphs from GitHub gap-packages. 
`./configure` failed at the first attempt (-bash: ./configure: No such file or directory) 
but succeeded after running `autogen.sh`.

**Comment by james-d-mitchell** [comment]
Good point, we can add some comments to the README.md about this.

**Comment by wilfwilson** [comment]
I added something to the README in v0.9.0
