### ISSUE TITLE
Digraphs does not load on Windows

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/Digraphs#86]
The following happens, despite the digraphs.so file is there:
```
gap> LoadPackage("dig");
───────────────────────────────────────────────────────────────────────────────────────────────────────────────
Loading  orb 4.7.6 (Methods to enumerate orbits)
by Juergen Mueller (http://www.math.rwth-aachen.de/~Juergen.Mueller),
   Max Neunhöffer (http://www-groups.mcs.st-and.ac.uk/~neunhoef), and
   Felix Noeske (http://www.math.rwth-aachen.de/~Felix.Noeske).
Homepage: https://gap-packages.github.io/orb
───────────────────────────────────────────────────────────────────────────────────────────────────────────────
───────────────────────────────────────────────────────────────────────────────────────────────────────────────
Loading  GRAPE 4.7 (GRaph Algorithms using PErmutation groups)
by Leonard H. Soicher (http://www.maths.qmul.ac.uk/~leonard/).
Homepage: http://www.maths.qmul.ac.uk/~leonard/grape/
───────────────────────────────────────────────────────────────────────────────────────────────────────────────
#W dlopen() error: No such file or directory
Error, module '/proc/cygdrive/C/gap4r8p8test/pkg/digraphs-0.10.1/bin/i686-pc-cygwin-gcc-default32/digraphs.so' not foun\
d in
  if not LOAD_DYN( arg[1], false )  then
    Error( "no support for dynamic loading" );
fi; at /proc/cygdrive/C/gap4r8p8test/lib/files.gd:579 called from
<function "LoadDynamicModule">( <arguments> )
 called from read-eval loop at line 25 of /proc/cygdrive/C/gap4r8p8test/pkg/digraphs-0.10.1/init.g
Error, was not in any namespace called from
LEAVE_NAMESPACE(  ); at /proc/cygdrive/C/gap4r8p8test/lib/package.gi:1212 called from
ReadPackage( pkgname, "init.g" ); at /proc/cygdrive/C/gap4r8p8test/lib/package.gi:1585 called from
<function "LoadPackage">( <arguments> )
 called from read-eval loop at line 1 of *stdin*
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue
brk> 
```

**Comment by james-d-mitchell** [comment]
Hmmm, I don't know how to debug this, since I don't have access to a Windows computer. 

Just to double check the file reported as not found is actually there?

**Comment by alex-konovalov** [comment]
yes, the binary is there, built under Cygwin. I suspect there maybe something about the initial part of the path (`/proc/cygdrive/C` vs `/cygdrive/C`). I can help to debug this from next week, mainly saving this so it's not forgotten. @jdebeule also sees this.

**Comment by ChrisJefferson** [comment]
proc/cygdrive is the “modern” way of access files in cygwin.

Chris

**Comment by ChrisJefferson** [comment]
How did you build this?

I tried just building master digraphs with master gap, and everything was fine.

**Comment by alex-konovalov** [comment]
This is GAP 4.8.8 installation, with official digraphs release included there. Build with `../bin/BuildPackages.sh` under Cygwin, and then installed on a Cygwin-free machine.

**Comment by james-d-mitchell** [comment]
@alex-konovalov @jdebeule @ChrisJefferson is this still an issue? Can anyone provide some more information that might help us resolve the issue if it persists?

**Comment by jdebeule** [comment]
Dear James,
dear Chris and Alexander,

I am unable to reproduce this problem on my installation of windows 10. In other words, digraphs loads fine. 

Cheers,

Jan

----------------------------------------------------------------------------
Jan De Beule                                                  jan@debeule.eu
Postdoctoraal onderzoeker
Vrije Universiteit Brussel
Vakgroep Wiskunde
Pleinlaan 2
B 1050 Brussel (Belgium)                http://homepages.vub.ac.be/~jdbeule/
----------------------------------------------------------------------------

**Comment by alex-konovalov** [comment]
@jdebeule do you install GAP and packages in Windows 10 Linux bash shell? If so, I would not be  surprised if it works. But the issue is when it is started on Windows with one of the `bat`-file in the `bin` directory.

**Comment by alex-konovalov** [comment]
P.S. I have just checked that the same happens with digraphs-0.10.1 and GAP as in the master branch.

**Comment by jdebeule** [comment]
Hi Alexander,

I just downloaded the pre-compiled version of GAP and all packages. 

Best regards,

Jan
----------------------------------------------------------------------------
Jan De Beule                                          Jan.De.Beule@vub.ac.be
Postdoctoraal onderzoeker
Vrije Universiteit Brussel
Vakgroep Wiskunde
Pleinlaan 2
B 1050 Brussel (Belgium)                 http://homepages.vub.ac.be/~jdbeule
----------------------------------------------------------------------------

**Comment by alex-konovalov** [comment]
The reason was in missing `cygstdc++-6.dll`, as suggested by @ChrisJefferson. I have now added this to the -win.zip archive, and both Digraphs and JSON now can be loaded on Windows. So for these two packages the problem will disappear in the next GAP distribution.

**Comment by alex-konovalov** [comment]
For the record, I am going to warp and publish GAP 4.8.10 with missing dll, that will provide working Digraphs for Windows. @james-d-mitchell if you can review https://github.com/gap-system/gap/pull/2089 to ensure that your packages are handled and described correctly, that would be helpful. Thanks!

**Comment by james-d-mitchell** [comment]
Thanks @alex-konovalov, everything looks great.
