### ISSUE TITLE
Add facility to set a filter when creating a digraph

### ISSUE THREAD

**Issue by wilfwilson** [gap-packages/Digraphs#88]
It would be useful, for instance for @mtorpey's work on posets of semigroup congruences, to be able to create a digraph object whilst simulatenously setting it to satisfy a particular filter. For Michael, this would be `IsCongruencePoset`. The interface could be something like:
```
gap> Digraph(nbs, IsCongruencePoset);
<poset of whatever>
```
Since we have a million ways of creating digraphs (various versions use `Digraph` itself, as well as `DigraphByAdjacenyMatrix`, `DigraphByInNeighbours`, etc), we'll need to think carefully about what we want to do.

**Comment by wilfwilson** [comment]
We've decided to abandon this issue (for now at least). It seems simple enough to simply do `SetFilterObj(obj, filter)`, which is how @mtorpey does it with his congruence posets.

It might be a bit better to pass a type rather than a filter, so that the digraph is objectified with that type rather than with `DigraphType` (currently all digraphs have the same family and type). But we didn't really see a use case for this.

**Comment by james-d-mitchell** [comment]
Agreed. I'm going to mark this as closed.
