### ISSUE TITLE
Refactor `DIGRAPHS_Bipartite` for better performance.

### ISSUE THREAD

**Issue by wilfwilson** [gap-packages/Digraphs#98]
We can find out whether a digraph is bipartite, and simultaneously obtain a 2-colouring for a bipartite digraph, by using a depth first search. Doing this would be much faster than the current implementation.

**Comment by wilfwilson** [comment]
@flsmith Am I correct in thinking that you were working on this at GAP Days last week?

**Comment by james-d-mitchell** [comment]
@wilfwilson yes, the improved version is in the `mutable` branch.
